require('prototypes/map-preset')
require('prototypes/fuels')
require('prototypes/energy-generators')
require('prototypes/voids')
require('prototypes/factories')
require('prototypes/miners')
require('prototypes/recipes')
